services:
  app:
    user: ${CURRENT_UNAME:-dev}
    build:
      args:
        user: ${CURRENT_UNAME:-dev}
        uid: ${CURRENT_UID:-1000}
      context: ./
      dockerfile: Dockerfile-dev
    image: framework-app:dev
    container_name: framework-app
    ports:
      - 3002:3002
    restart: unless-stopped
    working_dir: /opt/framework
    volumes:
      - ./app:/opt/framework
    networks:
      - framework-network

  nginx:
    image: nginx:bookworm
    container_name: framework-nginx
    restart: unless-stopped
    working_dir: /opt/framework
    ports:
      - 3000:80
      - 3003:443
    volumes:
      - ./app:/opt/framework
      - ./nginx/default.conf.dev:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/dev.crt:/etc/nginx/ssl/nginx.crt
      - ./nginx/ssl/dev.key:/etc/nginx/ssl/nginx.key
    networks:
      - framework-network

  db:
    image: mariadb:12.0.2
    # Sur Mac OS uniquement :
    # platform: linux/x86_64
    container_name: framework-db
    restart: unless-stopped
    # Ces variables sont définies dans le fichier .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - framework-network

  phpmyadmin:
    image: phpmyadmin
    container_name: framework-pma
    environment:
      PMA_HOST: framework-db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3001:80
    depends_on:
      - db
    networks:
      - framework-network

networks:
  framework-network:
    driver: bridge